### ISSUE TITLE
Role and user bounty gating

### ISSUE THREAD

**Issue by Behold3th** [Behold3th/discord-bots#4]
**Is your feature request related to a problem? Please describe.**
As a shareholder in the customer experience, I should drive to eliminate all frictions in the bounty creation process. One friction that Links and Jordaniza, through outreach work, have identified as a common is the desire to gate Bounties for a particular role tag (I.e. this Bounty is for Writer's Guild only, or for a particular list of users). This is also a friction for those wishing to claim such a bounty, as there is an extra and unnecessary layer of coordination going on here that looks like:

Creator: "Hey I'm going to create this bounty, but I'd like for only you to claim it. When are you going to be online so that you can claim it right away?"

Claimer: *scheduling dialogue

Creator: *scheduling dialogue

Creator: "Ok it's up!"

Claimer: *claims bounty

And in my personal experience, after discussing the unit of work with the individual, I sometimes just forget to make the bounty. 

**Describe the solution you'd like**
A subcommand of the Bounty create flow should include the ability to specify specific roles to gate the bounty, as well as individual users. Both roles and users should be noted with tagging (@[snowflake]). This should be two optional commands (perform type checking on the snowflakes with discord fetch commands), with arbitrary whitespace limits, except for newlines, carriage returns, and tabs, which will not be allowed. I propose `roles` as the first command word, and `users` as second. 

**Describe alternatives you've considered**
An alternative would be to have users and roles combined into one command, but I think that's a bit of a confusing user experience.

**Comment by jordaniza** [comment]
Agree with the solution as described. We might want to consider adding a new status: "Reserved" that creates a bounty for a single user, without polluting the "Open" category. It'll be a disappointing and frustrating experience to try and claim a bounty that is earmarked for another user.

For gated bounties, I suggest we really focus on making it clear with visual cues when a particular bounty has gating. This could be through a color in Bounty Bot, and maybe an accordion item color in the web UI

We will need to align the Bounty Bot with API + Frontend to ensure we achieve parity when creating a reserved bouty.
